logging:
  format: stdout    # Choose "json" or consol
  level: info       # Logging level: info, warn, error
  output: stdout    # Choose the output, "stdout" for console output or a filepath
tailscale:
  api_key: ""
  hostnmae: "TS_HOSTNAME"
dashboard:
  enabled: true
  token: CHANGEME
  port: :8001
services:
- name: test
  enabled: true
  routes:
  - type: tcp
    port: 8080
    machine:
      address: 192.168.0.104
      port: 30013
