tailscale:
  api_key: ""
  hostnmae: "TS_HOSTNAME"
dashboard:
  enabled: true
  username: admin
  password: CHANGEME
routes:
- name: example.domain.com
  type: http
  machine:
    address: 192.168.0.104
    port: 30013
- name: example tcp example
  type: tcp
  port: 8080
  machine:
    address: 192.168.0.104
    port: 30013
