tailscale:
  api_key: ""
  hostnmae: "TS_HOSTNAME"
dashboard:
  enabled: true
  password: CHANGEME
services:
- name: test
  enabled: true
  routes:
  - type: tcp
    port: 8080
    machine:
      address: 192.168.0.104
      port: 30013
