tailscale: 
  api_key: ""
  hostnmae: "tshello"

routes: 
  - name: truenas
    listen_port: 8001
    host: "192.168.0.104"
    port: 80

  - name: jellyfin
    listen_port: 8002
    host: "192.168.0.104"
    port: 30013