logging:
  format: stdout    # Choose "json" or consol
  level: info       # Logging level: info, warn, error
  output: stdout    # Choose the output, "stdout" for console output or a filepath
tailscale:
  api_key: ""
  hostnmae: "TS_HOSTNAME"
services:
- name: test
  enabled: true
  routes:
  - type: tcp
    port: 8080
    machine:
      address: 192.168.0.104
      port: 30013

database:
  connection_type: sqlite #  sqlite, postgress, mysql
  connection: file:warptail.db?cache=shared

application:
  port: 8080  # The main port the application listens on
  authentication:
    baseURL: http://localhost:8001
    secretKey: CHANGE_ME 
    provider: # Optional SSO provider configuration
      name: zitadle
      type: openid # Only openID with PKCE support is supported
      clientID: "<CLIENT_ID>"
      providerURL: "https://auth.example.com"
  acme: # Optional SSL 
    enabled: true  # Enable ACME SSL configuration
    ssl_port: 443  # Port for SSL/TLS connections
    certificates_dir: /etc/proxy/certs  # Directory to store SSL certificates
    portal_domain: warptail.excptionerror.local  # SSL domain for certificate 