apiVersion: apps/v1
kind: Deployment
metadata:
  name: warptail-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warptail
  template:
    metadata:
      labels:
        app: warptail
    spec:
      serviceAccountName: warptail
      automountServiceAccountToken: false
      containers:
        - name: warptail-container
          image: app-image:0.0.1
          resources:
            requests:
              ephemeral-storage: "150Mi"
              memory: 50Mi
              cpu: 0.5
            limits:
              ephemeral-storage: "200Mi"
              memory: 500Mi
          ports:
            - containerPort: 8081
          env:
            - name: CONFIG_PATH
              value: /app/config/config.yaml
              
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: warptail-configmap
            items:
              - key: config.yaml
                path: config.yaml
