apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: warptail-ingress-role
rules:
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "update", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: warptail-ingress-role-binding
subjects:
  - kind: ServiceAccount
    name: warptail
    namespace: default
roleRef:
  kind: ClusterRole
  name: warptail-ingress-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: warptail