apiVersion: v1
kind: Service
metadata:
  name: warptail-service
  labels:
    app: warptail
    release: prometheus
spec:
  selector:
    app: warptail
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
    