/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as UsersIndexRouteImport } from './routes/users/index'

const SettingsLazyRouteImport = createFileRoute('/settings')()
const ProfileLazyRouteImport = createFileRoute('/profile')()
const PasswordResetLazyRouteImport = createFileRoute('/password-reset')()
const LoginLazyRouteImport = createFileRoute('/login')()
const IndexLazyRouteImport = createFileRoute('/')()
const RoutesIndexLazyRouteImport = createFileRoute('/routes/')()
const RoutesServiceIndexLazyRouteImport = createFileRoute('/routes/$service/')()
const RoutesServiceEditLazyRouteImport = createFileRoute(
  '/routes/$service/edit',
)()

const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ProfileLazyRoute = ProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const PasswordResetLazyRoute = PasswordResetLazyRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/password-reset.lazy').then((d) => d.Route),
)
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const RoutesIndexLazyRoute = RoutesIndexLazyRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/routes/index.lazy').then((d) => d.Route))
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesServiceIndexLazyRoute = RoutesServiceIndexLazyRouteImport.update({
  id: '/routes/$service/',
  path: '/routes/$service/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/routes/$service/index.lazy').then((d) => d.Route),
)
const RoutesServiceEditLazyRoute = RoutesServiceEditLazyRouteImport.update({
  id: '/routes/$service/edit',
  path: '/routes/$service/edit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/routes/$service/edit.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/404': typeof R404Route
  '/login': typeof LoginLazyRoute
  '/password-reset': typeof PasswordResetLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/users': typeof UsersIndexRoute
  '/routes': typeof RoutesIndexLazyRoute
  '/routes/$service/edit': typeof RoutesServiceEditLazyRoute
  '/routes/$service': typeof RoutesServiceIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/404': typeof R404Route
  '/login': typeof LoginLazyRoute
  '/password-reset': typeof PasswordResetLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/users': typeof UsersIndexRoute
  '/routes': typeof RoutesIndexLazyRoute
  '/routes/$service/edit': typeof RoutesServiceEditLazyRoute
  '/routes/$service': typeof RoutesServiceIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/404': typeof R404Route
  '/login': typeof LoginLazyRoute
  '/password-reset': typeof PasswordResetLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/users/': typeof UsersIndexRoute
  '/routes/': typeof RoutesIndexLazyRoute
  '/routes/$service/edit': typeof RoutesServiceEditLazyRoute
  '/routes/$service/': typeof RoutesServiceIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/login'
    | '/password-reset'
    | '/profile'
    | '/settings'
    | '/users'
    | '/routes'
    | '/routes/$service/edit'
    | '/routes/$service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/password-reset'
    | '/profile'
    | '/settings'
    | '/users'
    | '/routes'
    | '/routes/$service/edit'
    | '/routes/$service'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/login'
    | '/password-reset'
    | '/profile'
    | '/settings'
    | '/users/'
    | '/routes/'
    | '/routes/$service/edit'
    | '/routes/$service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  R404Route: typeof R404Route
  LoginLazyRoute: typeof LoginLazyRoute
  PasswordResetLazyRoute: typeof PasswordResetLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  UsersIndexRoute: typeof UsersIndexRoute
  RoutesIndexLazyRoute: typeof RoutesIndexLazyRoute
  RoutesServiceEditLazyRoute: typeof RoutesServiceEditLazyRoute
  RoutesServiceIndexLazyRoute: typeof RoutesServiceIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$service/': {
      id: '/routes/$service/'
      path: '/routes/$service'
      fullPath: '/routes/$service'
      preLoaderRoute: typeof RoutesServiceIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$service/edit': {
      id: '/routes/$service/edit'
      path: '/routes/$service/edit'
      fullPath: '/routes/$service/edit'
      preLoaderRoute: typeof RoutesServiceEditLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  R404Route: R404Route,
  LoginLazyRoute: LoginLazyRoute,
  PasswordResetLazyRoute: PasswordResetLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  UsersIndexRoute: UsersIndexRoute,
  RoutesIndexLazyRoute: RoutesIndexLazyRoute,
  RoutesServiceEditLazyRoute: RoutesServiceEditLazyRoute,
  RoutesServiceIndexLazyRoute: RoutesServiceIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
